services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: fedoto
      POSTGRES_PASSWORD: fedoto
      POSTGRES_DB: fedoto
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  app:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://fedoto:fedoto@db:5432/fedoto
    depends_on:
      - db
    command: sh -c "npm run dev"

  worker:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://fedoto:fedoto@db:5432/fedoto
    depends_on:
      - redis
      - db
    command: sh -c "node ./src/worker.mjs"

volumes:
  pg_data:
