services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: fedoto
      POSTGRES_PASSWORD: fedoto
      POSTGRES_DB: fedoto
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://fedoto:fedoto@db:5432/fedoto
    depends_on:
      - db
    command: sh -c "npm install && npx prisma migrate deploy && npm run dev"

volumes:
  pg_data:
